name: "CI qemu cross"
on: [push, pull_request]
jobs:
    qemu-cross:
        strategy:
            matrix:
                include: [
                    { platform: s390x },
                    { platform: riscv64 },
                ]
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: docker/setup-qemu-action@v2

        - name: qemu ${{ matrix.platform }} build and test
          uses: ./.github/actions/qemu-cross
          with:
            platform: ${{ matrix.platform }}
